"""
Summarize results/bench_synthetic_payload.jsonl from bench.py --jsonl-out.

Usage:
    python summarize_bench_synthetic.py [--input results/bench_synthetic_payload.jsonl]
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Tuple

DEFAULT = Path("results/bench_synthetic_payload.jsonl")
OUT_MD = Path("results/bench_synthetic_payload_summary.md")


def load(path: Path) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    header: Dict[str, Any] = {}
    rows: List[Dict[str, Any]] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            o = json.loads(line)
            if o.get("type") == "bench_synthetic_header":
                header = o
            else:
                rows.append(o)
    return header, rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", type=Path, default=DEFAULT)
    ap.add_argument("--md", type=Path, default=OUT_MD)
    args = ap.parse_args()

    if not args.input.exists():
        print(f"Missing {args.input}; run: python bench.py --jsonl-out {args.input}")
        return

    header, rows = load(args.input)
    by_grid: Dict[Tuple[int, int], Dict[str, Any]] = defaultdict(dict)
    for r in rows:
        mode = r.get("mode")
        nr, nc = r.get("n_rows"), r.get("n_cols")
        if mode is None or nr is None or nc is None:
            continue
        key = (int(nr), int(nc))
        if mode == "json":
            by_grid[key]["json_bytes"] = r.get("response_bytes")
            by_grid[key]["json_e2e_s"] = r.get("end_to_end_s")
        elif mode == "parquet_blob":
            by_grid[key]["parquet_blob_bytes"] = r.get("bytes_downloaded")
            by_grid[key]["parquet_blob_e2e_s"] = r.get("end_to_end_s")
        elif mode == "parquet_stream":
            rpc = r.get("rows_per_chunk")
            by_grid[key][f"parquet_stream_bytes_chunk_{rpc}"] = r.get("bytes_read")
            by_grid[key][f"parquet_stream_e2e_s_chunk_{rpc}"] = r.get("end_to_end_s")

    lines = [
        "# Synthetic MCP benchmark — payload and latency",
        "",
        "Generated by `bench.py` (synthetic tabular data, no SQLite).",
        "",
        "## Configuration",
        "",
        f"```json\n{json.dumps(header, indent=2)}\n```",
        "",
        "## By grid shape (JSON vs Parquet blob)",
        "",
        "| n_rows | n_cols | JSON bytes | Parquet blob bytes | ratio JSON/blob |",
        "|--------|-------:|-----------:|-------------------:|----------------:|",
    ]

    for (nr, nc) in sorted(by_grid.keys()):
        g = by_grid[(nr, nc)]
        jb = g.get("json_bytes")
        pb = g.get("parquet_blob_bytes")
        ratio = ""
        if jb is not None and pb is not None and pb > 0:
            ratio = f"{float(jb) / float(pb):.2f}x"
        lines.append(
            f"| {nr:,} | {nc} | {jb if jb is not None else '—'} | {pb if pb is not None else '—'} | {ratio or '—'} |"
        )

    lines.extend(["", "*Lower ratio JSON/blob means Parquet is smaller on the wire (blob mode).*", ""])

    args.md.parent.mkdir(parents=True, exist_ok=True)
    args.md.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.md}")


if __name__ == "__main__":
    main()
